
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd9\xfe\x91\xc3<\xfd\xceTH\xad9\xd7\x01\x12\xca\x0f'
    
_lr_action_items = {'SEMI':([7,8,9,],[-4,-5,11,]),'INT':([5,],[7,]),'FLOAT':([5,],[8,]),'COMMA':([4,],[6,]),'VAR':([0,],[2,]),'COLON':([3,4,10,],[5,-3,-2,]),'ID':([2,6,],[4,4,]),'$end':([1,11,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'var':([2,6,],[3,10,]),'type':([5,],[9,]),'vars':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> vars","S'",1,None,None,None),
  ('vars -> VAR var COLON type SEMI','vars',5,'p_main','D:\\Projects\\Compiler\\ldy.py',7),
  ('var -> ID COMMA var','var',3,'p_vars_2','D:\\Projects\\Compiler\\ldy.py',10),
  ('var -> ID','var',1,'p_vars_2','D:\\Projects\\Compiler\\ldy.py',11),
  ('type -> INT','type',1,'p_type','D:\\Projects\\Compiler\\ldy.py',14),
  ('type -> FLOAT','type',1,'p_type','D:\\Projects\\Compiler\\ldy.py',15),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','D:\\Projects\\Compiler\\ldy.py',18),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','D:\\Projects\\Compiler\\ldy.py',22),
  ('expression -> term','expression',1,'p_expression_term','D:\\Projects\\Compiler\\ldy.py',26),
  ('term -> term TIMES factor','term',3,'p_term_times','D:\\Projects\\Compiler\\ldy.py',30),
  ('term -> term DIVIDE factor','term',3,'p_term_div','D:\\Projects\\Compiler\\ldy.py',34),
  ('term -> factor','term',1,'p_term_factor','D:\\Projects\\Compiler\\ldy.py',38),
  ('factor -> ICONST','factor',1,'p_factor_num','D:\\Projects\\Compiler\\ldy.py',42),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','D:\\Projects\\Compiler\\ldy.py',46),
]
